### ISSUE TITLE
None of the install methods work

### ISSUE THREAD

**Issue by nup002** [pyne/pyne#902]
I have tested the following guides to installing pyne:
http://pyne.io/install/conda.html#conda
The binary option for Windows fails, as conda is unable to find the package.
Create a package fails as the recipes folder does not contain a recipe for pyne.

http://pyne.io/install/vb.html#vb
Installation is not possible, since the link provided to download the virtualbox image is broken and tells me "The resource could not be found".
This is probably something someone in the development team should take a look at very soon. I would like to use pyne, but alas.

**Comment by makeclean** [comment]
I can't comment on the conda install, but I do know that we are having issues with out data hosting from data.pyne.io, so that should hopefully be addressed soon.

**Comment by scopatz** [comment]
I believe that we were hosting these files on a free rackspace account that they donated to the SciPy community.  It seems like they may have stopped supporting this, so we need to migrate.

I think we should probably go with something a little more transparent than a cloud CDN. I recommend creating a special "pyne/data" repo on github and shoving these files there.

Any comments or other proposals?

**Comment by katyhuff** [comment]
+1 to 
> creating a special "pyne/data" repo on github and shoving these files there.

**Comment by ivannovikov** [comment]
It looks like conda still is unable to find the package. What is the best way now to install pyne?

**Comment by scopatz** [comment]
@ivannovikov - can you please post your conda install output? We may need to rebuild the package for newer versions of numpy/python/etc.

**Comment by ivannovikov** [comment]
@scopatz It is resolved now. The problem was with my conda installation on mac. I can't tell you that pyne now works properly, but I did instal in on mac using conda.

**Comment by pedrojrv** [comment]
I am still facing this issue. Conda cannot find the package. This is in Windows 10. Any updates?

![image](https://user-images.githubusercontent.com/36640400/70489052-6daee980-1aaf-11ea-80e8-c083f5d11c3e.png)

**Comment by bam241** [comment]
Hi, I am not sure we support windows install.

More over the `PyNE` `conda` package is 2 years old...
my advice is to install dependencies using `conda` and then build  PyNE` from source (I have no experience building `PyNE` from source, but I'll happy to assist you, if I can
